# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="3os"

# Plugins
plugins=(git colored-man-pages docker docker-compose iterm2 node npm brew colorize macos pip pyenv virtualenv adb aws command-not-found zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Aliases
alias reboot="sudo reboot"
alias poweroff="sudo poweroff"
alias kiauh='/home/pi/kiauh/kiauh.sh'
alias git-push='git add . && git commit -m $(date +'%Y%m%d.%H%M') && git push'
alias klipper-restart='systemctl restart klipper'

# bpytop aliases
if which bpytop >/dev/null; then
  alias htop='bpytop'
  alias top='bpytop'
fi


# Screenfetch
if which screenfetch >/dev/null; then
  screenfetch
fi

## Fix for Slow zsh-autosuggestions copy&paste
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic
zstyle ':bracketed-paste-magic' active-widgets '.self-*'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true

# Usage Message:

echo "Usage:"
echo "Klipper Restart: $klipper-restart"